from typing import Protocol, Dict, Any

class CancellationToken(Protocol):
    def is_cancelled_sync(self) -> bool: ...
    async def is_cancelled(self) -> bool: ...

class EventBus(Protocol):
    def publish_sync(self, payload: Dict[str, Any]) -> None: ...
    async def publish_async(self, payload: Dict[str, Any]) -> None: ...

class OCRReporter(Protocol):
    def log(self, message: str) -> None: ...
    def progress(self, current: int, total: int, eta: str) -> None: ...
    def subtitle(self, item: Dict[str, Any]) -> None: ...
    def set_total(self, total: int) -> None: ...
    def done(self) -> None: ...