from typing import Protocol, Dict, Any
from rendering.interfaces import CancellationToken

class OCRReporter(Protocol):
    def log(self, message: str) -> None: ...
    def progress(self, current: int, total: int, eta: str) -> None: ...
    def subtitle(self, item: Dict[str, Any]) -> None: ...
    def set_total(self, total: int) -> None: ...
    def done(self) -> None: ...