from typing import Protocol, Callable, Awaitable

class Reporter(Protocol):
    async def log(self, message: str) -> None: ...
    async def progress(self, current: int, total: int, eta: str) -> None: ...
    async def done(self, total: int) -> None: ...

class Storage(Protocol):
    async def download(self, key: str, dest: str) -> bool: ...
    async def upload(self, src: str, key: str) -> bool: ...

class CancellationToken(Protocol):
    async def is_cancelled(self) -> bool:
        """Return True if cancellation has been requested."""
        ...

CancelCheck = Callable[[], Awaitable[bool]]