from typing import Protocol, Callable

class Reporter(Protocol):
    def log(self, message: str) -> None: ...
    def progress(self, current: int, total: int, eta: str) -> None: ...
    def done(self, total: int) -> None: ...

class Storage(Protocol):
    async def download(self, key: str, dest: str) -> bool: ...
    async def upload(self, src: str, key: str) -> bool: ...

class CancellationToken(Protocol):
    def is_cancelled_sync(self) -> bool: ...

CancelCheck = Callable[[], bool]